name: AUTO DEPLOY CONTAINER

# env:
#    DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
#    USERNAME: yourhubusername
#    REPOSITORY_NAME: yourrepositoryname

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        run: docker login --username=henrymarks --password=Henrymarks0429
      - name: Build Image
        run: docker build -t $henrymarks/tox-bot:autodeploy .
      - name: Push Image
        run: docker push henrymarks/tox-bot:autodeploy
